In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 

df = pd.read_csv(r"C:\Users\dell\Desktop\MBGP Mentoring\Programming\Excel Data\Automobile_data.csv")
print(df.info())
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             61 non-null     int64
 1   company           61 non-null     object
 2   body-style        61 non-null     object
 3   wheel-base        61 non-null     float64
 4   length            61 non-null     float64
 5   engine-type       61 non-null     object
 6   num-of-cylinders  61 non-null     object
 7   horsepower        61 non-null     int64
 8   average-mileage   61 non-null     int64
 9   price             58 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 4.9+ KB
None

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0

In [2]:
#1. What is the average price and average mileage for convertible cars

df_s1 = df[df["body-style"] == "convertible"]
df_sol1 = pd.DataFrame(df_s1[["price","average-mileage"]].mean().__round__(3), columns=["Average Value"]).reset_index()

df_sol1 = df_sol1.rename(columns={"index":"Variable"})

df_sol1

          Variable  Average Value
0            price      22341.000
1  average-mileage         19.667

In [3]:
#2.Sort cars by company and price in descending order
df_sol2 = df.sort_values(by=["company", "price"], ascending=False)
df_sol2

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
...,...,...,...,...,...,...,...,...,...,...
5,5,audi,sedan,99.8,177.3,ohc,five,110,19,15250.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0

In [4]:
#3.Save data for 'Toyota' separately
df_sol3 = df[df["company"] == "toyota"]
df_sol3

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
48,66,toyota,hatchback,95.7,158.7,ohc,four,62,35,5348.0
49,67,toyota,hatchback,95.7,158.7,ohc,four,62,31,6338.0
50,68,toyota,hatchback,95.7,158.7,ohc,four,62,31,6488.0
51,69,toyota,wagon,95.7,169.7,ohc,four,62,31,6918.0
52,70,toyota,wagon,95.7,169.7,ohc,four,62,27,7898.0
53,71,toyota,wagon,95.7,169.7,ohc,four,62,27,8778.0
54,79,toyota,wagon,104.5,187.8,dohc,six,156,19,15750.0

In [5]:
# 4.Which company is producing most expensive car?
df_sol4 = df [df["price"].max() == df["price"]]
df_sol4

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
35,47,mercedes-benz,hardtop,112.0,199.2,ohcv,eight,184,14,45400.0

In [6]:
#5. Name the cars on basis of maximum length, highest wheelbase, maximum horsepower
required_items = ["length", "wheel-base", "horsepower"]
df_sol5 = pd.DataFrame()
for i in required_items:
    df_temp = pd.DataFrame(df[df[i] == df[i].max()]["company"])
    df_temp["Variable"] = i
    df_temp["Value"] = df[i].max()
    df_sol5 = pd.concat([df_sol5,df_temp])

df_sol5

          company    Variable  Value
34  mercedes-benz      length  208.1
34  mercedes-benz  wheel-base  120.9
47        porsche  horsepower  288.0

In [7]:
#6. company wise average price of cars and order them in descending order
df_sol6 = pd.DataFrame(df.groupby(by=["company"])["price"].mean())
df_sol6 = df_sol6.sort_values(by=["price"], ascending=False).round(3)

df_sol6

                   price
company
porsche        35528.000
mercedes-benz  35040.000
jaguar         34600.000
bmw            27213.333
audi           16392.500
alfa-romero    15498.333
volvo          13177.500
honda          10195.000
mazda           9654.800
volkswagen      8435.000
nissan          8289.000
toyota          8216.857
isuzu           6785.000
mitsubishi      6689.000
dodge           6303.000
chevrolet       6007.000

In [8]:
#7. create a column named: "decision", If wheel-base is less than 100 and length is less than 175 then "don't buy" else "buy"

df["decision"] = np.where(((df["wheel-base"]<100) & (df["length"]<175)), "Don't Buy", "Buy")

df

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,decision
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0,Don't Buy
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0,Don't Buy
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0,Don't Buy
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0,Buy
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0,Buy
...,...,...,...,...,...,...,...,...,...,...,...
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0,Don't Buy
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0,Don't Buy
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0,Don't Buy
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0,Buy
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0,Buy

In [9]:
#8. Select only cars whose decision is "buy"; find average price based on company of car

df_sol8 = df[df["decision"] == "Buy"][["company", "price", "decision"]]
df_sol8 = df_sol8.groupby(by=["company"], as_index=False)["price"].mean().round(2)
df_sol8

         company     price
0           audi  16392.50
1            bmw  27213.33
2          honda  12945.00
3         jaguar  34600.00
4          mazda  18344.00
5  mercedes-benz  35040.00
6         nissan  13499.00
7        porsche       NaN
8         toyota  15750.00
9          volvo  13177.50

In [10]:
#9. Save all the solutions in single Excel File.

writer = pd.ExcelWriter(r"C:\Users\dell\Desktop\MBGP Mentoring\Programming\Excel Data\Automobile Data Summary.xlsx", engine = "xlsxwriter")

df_sol1.to_excel(writer,sheet_name = "Solution 1", index = False)
df_sol2.to_excel(writer,sheet_name = "Solution 2", index = False)
df_sol3.to_excel(writer,sheet_name = "Solution 3", index = False)
df_sol4.to_excel(writer,sheet_name = "Solution 4", index = False)
df_sol5.to_excel(writer,sheet_name = "Solution 5", index = False)
df_sol6.to_excel(writer,sheet_name = "Solution 6", index = False)
df.to_excel(writer,sheet_name = "Solution 7 ", index = False)
df_sol8.to_excel(writer,sheet_name = "Solution 8", index = False)

In [14]:
writer.close()

c:\Users\dell\Desktop\MBGP Mentoring\Programming\Learn Python\.venv\Lib\site-packages\xlsxwriter\workbook.py:404: UserWarning: Calling close() on already closed file.
  warn("Calling close() on already closed file.")

In [16]:
pd.read_excel(r"C:\Users\dell\Desktop\MBGP Mentoring\Programming\Excel Data\Automobile Data Summary.xlsx", sheet_name = "Solution 1")

          Variable  Average Value
0            price      22341.000
1  average-mileage         19.667